// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | GalleryGridSlice
  | ServiceEntrySlice
  | StorySectionSlice
  | FeaturesBentoSlice
  | ContactFormSlice
  | AboutHeroSlice
  | RichTextSlice
  | HeroSlice
  | ServicesSlice
  | AboutSlice
  | TeamSlice
  | TestimonialsSlice
  | CallToActionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation Links*
 */
export interface SettingsDocumentDataNavItemItem {
  /**
   * Label field in *Settings → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Home
   * - **API ID Path**: settings.nav_item[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_item[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Specchiami
   * - **API ID Path**: settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_name: prismic.KeyTextField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  nav_item: prismic.GroupField<Simplify<SettingsDocumentDataNavItemItem>>; /**
   * Footer Text field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short description or tagline...
   * - **API ID Path**: settings.footer_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_text: prismic.RichTextField;

  /**
   * Contact Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: info@example.com
   * - **API ID Path**: settings.contact_email
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Contact Phone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +39 000 000 0000
   * - **API ID Path**: settings.contact_phone
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_phone: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Primary content in *About → Image Right → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Eyebrow field in *About → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Chi siamo
   * - **API ID Path**: about.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *About → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: La nostra storia...
   * - **API ID Path**: about.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *About → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Racconta la storia del brand...
   * - **API ID Path**: about.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *About → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Button Label field in *About → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contattaci
   * - **API ID Path**: about.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *About → Image Right → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Image Right variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text on the left, image on the right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *About → Image Left → Primary*
 */
export interface AboutSliceImageLeftPrimary {
  /**
   * Eyebrow field in *About → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Chi siamo
   * - **API ID Path**: about.imageLeft.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *About → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: La nostra storia...
   * - **API ID Path**: about.imageLeft.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *About → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Racconta la storia del brand...
   * - **API ID Path**: about.imageLeft.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *About → Image Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.imageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Button Label field in *About → Image Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contattaci
   * - **API ID Path**: about.imageLeft.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *About → Image Left → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.imageLeft.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Image Left variation for About Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Image on the left, text on the right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<AboutSliceImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault | AboutSliceImageLeft;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: Two-column about section with text and image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Primary content in *AboutHero → Default → Primary*
 */
export interface AboutHeroSliceDefaultPrimary {
  /**
   * Heading (use italic for accent word) field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: The Art of Reflection
   * - **API ID Path**: about_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body text field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We believe that capturing memories should be as elegant as the events themselves.
   * - **API ID Path**: about_hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Link label field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Discover Our Story
   * - **API ID Path**: about_hero.default.primary.link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link anchor ID field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: our-story
   * - **API ID Path**: about_hero.default.primary.link_anchor
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_anchor: prismic.KeyTextField;

  /**
   * Main hero image field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Floating accent image (small) field in *AboutHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_hero.default.primary.accent_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  accent_image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutHero*
 */
type AboutHeroSliceVariation = AboutHeroSliceDefault;

/**
 * AboutHero Shared Slice
 *
 * - **API ID**: `about_hero`
 * - **Description**: Asymmetric hero with italic heading, body, link, large main image, and floating accent image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutHeroSlice = prismic.SharedSlice<
  "about_hero",
  AboutHeroSliceVariation
>;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Heading field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Prenota il tuo appuntamento
   * - **API ID Path**: call_to_action.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Messaggio di supporto al CTA...
   * - **API ID Path**: call_to_action.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Button Label field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contattaci ora
   * - **API ID Path**: call_to_action.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Dark CTA banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: Centered CTA banner with heading, body text, and a button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Heading field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get in Touch
   * - **API ID Path**: contact_form.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Intro text field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: We would love to hear from you. Please fill out the form below...
   * - **API ID Path**: contact_form.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro: prismic.KeyTextField;

  /**
   * Contact email field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: hello@specchiami.it
   * - **API ID Path**: contact_form.default.primary.contact_email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Contact phone field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +39 012 345 6789
   * - **API ID Path**: contact_form.default.primary.contact_phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_phone: prismic.KeyTextField;

  /**
   * Footer note (italic) field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Available for events across Italy and select European destinations.
   * - **API ID Path**: contact_form.default.primary.footer_note
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_note: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: Enquiry form with contact details sidebar
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *FeaturesBento → Default → Primary*
 */
export interface FeaturesBentoSliceDefaultPrimary {
  /**
   * Section heading field in *FeaturesBento → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Not Just a Booth. An Experience.
   * - **API ID Path**: features_bento.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_heading: prismic.KeyTextField;

  /**
   * Section body field in *FeaturesBento → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Elevate your event with a seamless blend of heritage aesthetics and modern interactive technology.
   * - **API ID Path**: features_bento.default.primary.section_body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_body: prismic.KeyTextField;
}

/**
 * Primary content in *FeaturesBento → Items*
 */
export interface FeaturesBentoSliceDefaultItem {
  /**
   * Icon (emoji or symbol name) field in *FeaturesBento → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 📷
   * - **API ID Path**: features_bento.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Card title field in *FeaturesBento → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Editorial Quality Capture
   * - **API ID Path**: features_bento.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Card body field in *FeaturesBento → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Studio-grade lighting and high-resolution cameras...
   * - **API ID Path**: features_bento.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;

  /**
   * Card image (optional) field in *FeaturesBento → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features_bento.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Card style field in *FeaturesBento → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: warm
   * - **Default Value**: warm
   * - **API ID Path**: features_bento.items[].card_style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  card_style: prismic.SelectField<
    "warm" | "cool" | "image-overlay" | "accent",
    "filled"
  >;
}

/**
 * Default variation for FeaturesBento Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesBentoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesBentoSliceDefaultPrimary>,
  Simplify<FeaturesBentoSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturesBento*
 */
type FeaturesBentoSliceVariation = FeaturesBentoSliceDefault;

/**
 * FeaturesBento Shared Slice
 *
 * - **API ID**: `features_bento`
 * - **Description**: 12-column bento grid of feature cards with icons, text, and optional images
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesBentoSlice = prismic.SharedSlice<
  "features_bento",
  FeaturesBentoSliceVariation
>;

/**
 * Primary content in *GalleryGrid → Default → Primary*
 */
export interface GalleryGridSliceDefaultPrimary {
  /**
   * Page heading field in *GalleryGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Moments of Magic
   * - **API ID Path**: gallery_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Intro text field in *GalleryGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Explore a curated selection of events where Specchiami added a touch of interactive elegance.
   * - **API ID Path**: gallery_grid.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro: prismic.KeyTextField;
}

/**
 * Primary content in *GalleryGrid → Items*
 */
export interface GalleryGridSliceDefaultItem {
  /**
   * Photo field in *GalleryGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_grid.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *GalleryGrid → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: weddings
   * - **Default Value**: weddings
   * - **API ID Path**: gallery_grid.items[].category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<"weddings" | "corporate" | "parties", "filled">;

  /**
   * Venue / event name (shown on hover) field in *GalleryGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Villa del Lago
   * - **API ID Path**: gallery_grid.items[].venue_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  venue_name: prismic.KeyTextField;
}

/**
 * Default variation for GalleryGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GalleryGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalleryGridSliceDefaultPrimary>,
  Simplify<GalleryGridSliceDefaultItem>
>;

/**
 * Slice variation for *GalleryGrid*
 */
type GalleryGridSliceVariation = GalleryGridSliceDefault;

/**
 * GalleryGrid Shared Slice
 *
 * - **API ID**: `gallery_grid`
 * - **Description**: Masonry photo gallery with category filter tabs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GalleryGridSlice = prismic.SharedSlice<
  "gallery_grid",
  GalleryGridSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Reflect the Magic of Your Most Special Moments
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Luxury Mirror Photobooth Rentals for Weddings, Parties, and Corporate Events.
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;

  /**
   * Primary CTA label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enquire Now
   * - **API ID Path**: hero.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Primary CTA link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View Gallery
   * - **API ID Path**: hero.default.primary.secondary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_cta_label: prismic.KeyTextField;

  /**
   * Secondary CTA link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Hero image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Split hero: heading + body + 2 CTAs on the left, image on the right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *ServiceEntry → Default → Primary*
 */
export interface ServiceEntrySliceDefaultPrimary {
  /**
   * Page heading field in *ServiceEntry → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Our Services
   * - **API ID Path**: service_entry.default.primary.page_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_heading: prismic.RichTextField;

  /**
   * Page intro text field in *ServiceEntry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Elevate your events with our sophisticated magic mirror experiences.
   * - **API ID Path**: service_entry.default.primary.page_intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_intro: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceEntry → Items*
 */
export interface ServiceEntrySliceDefaultItem {
  /**
   * Number / category label field in *ServiceEntry → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 01 / Weddings
   * - **API ID Path**: service_entry.items[].number_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  number_label: prismic.KeyTextField;

  /**
   * Service heading field in *ServiceEntry → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Timeless Memories
   * - **API ID Path**: service_entry.items[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Service body field in *ServiceEntry → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Capture the magic of your special day...
   * - **API ID Path**: service_entry.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;

  /**
	 * Feature checklist field in *ServiceEntry → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Studio-grade lighting
	Custom digital overlays...
	 * - **API ID Path**: service_entry.items[].bullet_items
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
  bullet_items: prismic.RichTextField;

  /**
   * CTA label field in *ServiceEntry → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book this Service
   * - **API ID Path**: service_entry.items[].cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA link field in *ServiceEntry → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_entry.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Service image field in *ServiceEntry → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_entry.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image position field in *ServiceEntry → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: left
   * - **Default Value**: left
   * - **API ID Path**: service_entry.items[].image_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_position: prismic.SelectField<"left" | "right", "filled">;
}

/**
 * Default variation for ServiceEntry Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceEntrySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceEntrySliceDefaultPrimary>,
  Simplify<ServiceEntrySliceDefaultItem>
>;

/**
 * Slice variation for *ServiceEntry*
 */
type ServiceEntrySliceVariation = ServiceEntrySliceDefault;

/**
 * ServiceEntry Shared Slice
 *
 * - **API ID**: `service_entry`
 * - **Description**: Full-width alternating service sections with image, number label, heading, checklist, and CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceEntrySlice = prismic.SharedSlice<
  "service_entry",
  ServiceEntrySliceVariation
>;

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Eyebrow field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: I nostri servizi
   * - **API ID Path**: services.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Cosa offriamo
   * - **API ID Path**: services.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Services → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Breve descrizione della sezione...
   * - **API ID Path**: services.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
  /**
   * Icon field in *Services → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Service Name field in *Services → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome servizio
   * - **API ID Path**: services.items[].service_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_name: prismic.KeyTextField;

  /**
   * Description field in *Services → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descrizione del servizio...
   * - **API ID Path**: services.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Grid of service cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  Simplify<ServicesSliceDefaultItem>
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services grid with icon, name, and description per card
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Primary content in *StorySection → Default → Primary*
 */
export interface StorySectionSliceDefaultPrimary {
  /**
   * Section heading field in *StorySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Beyond the Photobooth
   * - **API ID Path**: story_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Anchor ID (for internal links) field in *StorySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: our-story
   * - **API ID Path**: story_section.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * First paragraph field in *StorySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.default.primary.paragraph_1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph_1: prismic.RichTextField;

  /**
   * Middle image field in *StorySection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.default.primary.middle_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  middle_image: prismic.ImageField<never>;

  /**
   * Second paragraph field in *StorySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: story_section.default.primary.paragraph_2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph_2: prismic.RichTextField;
}

/**
 * Default variation for StorySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StorySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StorySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StorySection*
 */
type StorySectionSliceVariation = StorySectionSliceDefault;

/**
 * StorySection Shared Slice
 *
 * - **API ID**: `story_section`
 * - **Description**: Sticky headline on left, long-form narrative with inline image on right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StorySectionSlice = prismic.SharedSlice<
  "story_section",
  StorySectionSliceVariation
>;

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Eyebrow field in *Team → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Il nostro team
   * - **API ID Path**: team.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Le persone dietro il brand
   * - **API ID Path**: team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Presentazione del team...
   * - **API ID Path**: team.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Team → Items*
 */
export interface TeamSliceDefaultItem {
  /**
   * Photo field in *Team → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.items[].photo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  photo: prismic.ImageField<never>;

  /**
   * Name field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome Cognome
   * - **API ID Path**: team.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *Team → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Specialista Benessere
   * - **API ID Path**: team.items[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Bio field in *Team → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Breve biografia...
   * - **API ID Path**: team.items[].bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Grid of team cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  Simplify<TeamSliceDefaultItem>
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team member cards with photo, name, role, and bio
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Eyebrow field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cosa dicono di noi
   * - **API ID Path**: testimonials.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Le parole dei nostri clienti
   * - **API ID Path**: testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Quote field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: La testimonianza del cliente...
   * - **API ID Path**: testimonials.items[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Author Name field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nome Cliente
   * - **API ID Path**: testimonials.items[].author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Role / Location field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cliente abituale
   * - **API ID Path**: testimonials.items[].author_role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_role: prismic.KeyTextField;

  /**
   * Author Photo field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].author_photo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  author_photo: prismic.ImageField<never>;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Grid of testimonial cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Customer testimonial cards with quote, author name, role, and photo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavItemItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceImageLeftPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      AboutSliceImageLeft,
      AboutHeroSlice,
      AboutHeroSliceDefaultPrimary,
      AboutHeroSliceVariation,
      AboutHeroSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      FeaturesBentoSlice,
      FeaturesBentoSliceDefaultPrimary,
      FeaturesBentoSliceDefaultItem,
      FeaturesBentoSliceVariation,
      FeaturesBentoSliceDefault,
      GalleryGridSlice,
      GalleryGridSliceDefaultPrimary,
      GalleryGridSliceDefaultItem,
      GalleryGridSliceVariation,
      GalleryGridSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ServiceEntrySlice,
      ServiceEntrySliceDefaultPrimary,
      ServiceEntrySliceDefaultItem,
      ServiceEntrySliceVariation,
      ServiceEntrySliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimary,
      ServicesSliceDefaultItem,
      ServicesSliceVariation,
      ServicesSliceDefault,
      StorySectionSlice,
      StorySectionSliceDefaultPrimary,
      StorySectionSliceVariation,
      StorySectionSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimary,
      TeamSliceDefaultItem,
      TeamSliceVariation,
      TeamSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
