/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#4e4639',
        'primary': '#775a19',
        'on-primary': '#ffffff',
        'primary-container': '#c5a059',
        'on-primary-container': '#4e3700',
        'primary-fixed': '#ffdea5',
        'primary-fixed-dim': '#e9c176',
        'inverse-primary': '#e9c176',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'outline': '#7f7667',
        'outline-variant': '#d1c5b4',
        'background': '#fcf9f8',
        'on-background': '#1c1b1b',
        'secondary': '#5e5e5b',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1dfdb',
        'on-secondary-container': '#63635f',
        'tertiary': '#625e55',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#aaa59a',
        'on-tertiary-container': '#3e3b33',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface-tint': '#775a19',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'gutter': '24px',
        'section-gap': '120px',
        'margin-desktop': '80px',
        'container-max': '1280px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'display-lg': ['var(--font-playfair)', '"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg': ['var(--font-playfair)', '"Playfair Display"', 'Georgia', 'serif'],
        'headline-md': ['var(--font-playfair)', '"Playfair Display"', 'Georgia', 'serif'],
        'headline-sm': ['var(--font-playfair)', '"Playfair Display"', 'Georgia', 'serif'],
        'headline-lg-mobile': ['var(--font-playfair)', '"Playfair Display"', 'Georgia', 'serif'],
        'body-lg': ['var(--font-dm-sans)', '"DM Sans"', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-dm-sans)', '"DM Sans"', 'system-ui', 'sans-serif'],
        'label-md': ['var(--font-dm-sans)', '"DM Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
